Error: An item ID should not start or end with whitespace! ID: ' A', file <FILE>, line 2, col 5
Error: Illegal symbols found in an item ID! ID: '\tA1', file <FILE>, line 4, col 5
Error: An item ID should not start or end with whitespace! ID: 'B ', file <FILE>, line 6, col 5
Error: Illegal symbols found in an item ID! ID: 'C\n', file <FILE>, line 8, col 5
Error: Illegal symbols found in an item name! Name: 'D\n', file <FILE>, line 10, col 5
