Error: An object's ID duplicates another object's ID. ID='A', file <FILE>, line 4, col 1
Note: The object mentioned above: file <FILE>, line 2, col 1
Error: An object's ID duplicates another object's name. ID/name='A', file <FILE>, line 4, col 1
Note: The object mentioned above: file <FILE>, line 2, col 1
Error: An object's ID duplicates another object's ID. ID='A', file <FILE>, line 6, col 1
Note: The object mentioned above: file <FILE>, line 2, col 1
Error: An object's ID duplicates another object's name. ID/name='A', file <FILE>, line 6, col 1
Note: The object mentioned above: file <FILE>, line 2, col 1
Error: An object's ID duplicates another object's name. ID/name='C', file <FILE>, line 10, col 1
Note: The object mentioned above: file <FILE>, line 8, col 1
Error: An object's name duplicates another object's ID. Name/ID='D', file <FILE>, line 10, col 1
Note: The object mentioned above: file <FILE>, line 8, col 1
Error: An object's ID duplicates another object's ID. ID='D', file <FILE>, line 12, col 1
Note: The object mentioned above: file <FILE>, line 8, col 1
Error: An object's name duplicates another object's name. name='C', file <FILE>, line 14, col 1
Note: The object mentioned above: file <FILE>, line 8, col 1
